require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  DisplayCopNames: true
  Exclude:
    - '**/._*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
