inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  DisplayCopNames: true
  Exclude:
    - '**/._*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false
