language: ruby
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install:
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RUBYOPT=$RSPEC_RUBYOPT bundle exec rspec
  - bundle exec ruby examples/all.rb
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
  - test
  - lint
jobs:
  include:
    - stage: lint
      rvm: 2.2.2
      name: rubocop
      script: bundle exec rubocop
    - stage: lint
      rvm: 2.2.2
      name: rubydoctest
      script: bundle exec rubydoctest README.md
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: M8VEihBaynGJdlXu7TvhgqIDfpHvSP5H0RCLsvtaQ5rNoz6yrOTRcLBCWazrJopD1CvKbcFTVVLlS86fxyW9+pYhYc81mXlhtyPLNx7yXQ+Uhfrxp7/e2QLEMZEgbk2Z7XglN4rJ+t4QhWjsPL0ohJk+t1DSdFtEPK3o3RyoRrE=
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RSPEC_RUBYOPT="--jit"
    - rvm: ruby-head
      env: RSPEC_RUBYOPT="--jit"
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=8e9db6ee5f3818e87287a6393086c2ccb9b1b83106c5bfb972211abefd2fe162
