cure_grace: &cure_grace
  girl_name:    cure_grace
  human_name:   花寺 のどか
  precure_name: キュアグレース
  cast_name:    悠木 碧
  color:        pink
  created_date: 2020-02-02 # episode 1
  birthday:     3/9
  title:        花のプリキュア
  nicknames:
    - のどかっち
  transform_message: |-
    スタンバイ！
    プリキュアオペレーション！
    エレメントレベル上昇ラビ！
    キュアタッチ！
    キュア！
    キュア！
    重なる二つの花！キュアグレース！
    ラビ！
    地球をお手当！ヒーリングっど♥プリキュア！
  # extra_names:
  attack_messages:
    - |-
      エレメントチャージ！
      キュア！キュア！キュア！
      ヒーリングゲージ上昇！
      プリキュア！ヒーリングフラワー！
      お大事に
  transform_calls:
    - precure_operation
grace:
  <<: *cure_grace

cure_fontaine: &cure_fontaine
  girl_name:    cure_fontaine
  human_name:   沢泉 ちゆ
  precure_name: キュアフォンテーヌ
  cast_name:    依田 菜津
  color:        blue
  created_date: 2020-02-16 # episode 3
  birthday:     8/21
  title:        水のプリキュア
  nicknames:
    - ちゆちー
  transform_message: |-
    スタート！
    プリキュアオペレーション！
    エレメントレベル上昇ペ！
    キュアタッチ！
    キュ！
    キュ！
    交わる二つの流れ、キュアフォンテーヌ！
    ぺ！
    地球をお手当！ヒーリングっど♥プリキュア！
  # extra_names:
  attack_messages:
    - |-
      エレメントチャージ！
      キュ！キュ！キュ！
      ヒーリングゲージ上昇！
      プリキュア！ヒーリングストリーム！
      お大事に
  transform_calls:
    - precure_operation
fontaine:
  <<: *cure_fontaine

cure_sparkle: &cure_sparkle
  girl_name:    cure_sparkle
  human_name:   平光 ひなた
  precure_name: キュアスパークル
  cast_name:    河野 ひより
  color:        yellow
  created_date: 2020-02-23 # episode 4
  birthday:     10/4
  title:        光のプリキュア
  transform_message: |-
    スタート！
    プリキュアオペレーション！
    エレメントレベル上昇ニャ！
    キュアタッチ！
    キュン！
    キュン！
    溶け合う二つの光、キュアスパークル！
    ニャ！
    地球をお手当！ヒーリングっど♥プリキュア！
  # extra_names:
  attack_messages:
    - |-
      エレメントチャージ！
      キュン！キュン！キュン！
      ヒーリングゲージ上昇！
      プリキュア！ヒーリングフラッシュ！
      お大事に
  transform_calls:
    - precure_operation
sparkle:
  <<: *cure_sparkle

cure_earth: &cure_earth
  girl_name:    cure_earth
  human_name:   風鈴 アスミ
  precure_name: キュアアース
  cast_name:    三森 すずこ
  color:        purple
  created_date: 2020-08-09 # episode 19
  birthday: 8/16
  title:        風のプリキュア
  nicknames:
    - あすみん
    - アースっち
  transform_message: |-
    スタート！
    プリキュアオペレーション！
    エレメントレベル上昇ラテ！
    キュアタッチ！
    キュン！
    キュン！
    時を経て繋がる二つの風、キュアアース！
    ワン！
    地球をお手当！ヒーリングっど♥プリキュア！
  # extra_names:
  attack_messages:
    - |-
      アースウィンディハープ！
      エレメントチャージ！
      舞い上がれ、癒やしの風！
      プリキュア・ヒーリングハリケーン！
      お大事に
  transform_calls:
    - precure_operation
earth:
  <<: *cure_earth
